BNFDESCRIPTION    -> DEFINITION | DEFINITION BNFDESCRIPTION .
DEFINITION        -> NONTERMINAL '::=' EXPRESSION .
EXPRESSION        -> SEQUENCE | SEQUENCE '|' RIGHTHANDSIDE | .
SEQUENCE          -> TERM | TERM SEQUENCE .
TERM              -> NONTERMINAL | STRING .
NONTERMINAL       -> IDENTIFIER .
STRING            -> 'characters' | "characters" .
